title: REFLEX Project Page
description: Reinforcement Feedback Learning with LLMs for E-commerce Query Expansion
baseurl: ""
url: "https://zyp5511.github.io"
markdown: kramdown
kramdown:
  input: GFM
exclude:
  - README.md
